services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sport
      POSTGRES_PASSWORD: sport
      POSTGRES_DB: sport_app
    volumes:
      - sport_app_pg:/var/lib/postgresql/data

volumes:
  sport_app_pg:
